# for now, s3-tests requires py2
os_type: ubuntu
tasks:
- install:
- ceph:
- rgw: [client.0]
- s3tests:
    client.0:
      git_remote: git://github.com/theanalyst/
      force-branch: public-access-qa
      rgw_server: client.0
overrides:
  ceph:
    conf:
      client:
        rgw lc debug interval: 10
